#pragma once

#define HSML_TOKEN_SYMBOL  '\\'
#define HSML_TOKEN_COMMENT '#'
#define HSML_TOKEN_DELIMITER ';'

#define HSML_TOKEN_PLACEHOLDER '%'
#define HSML_TOKEN_PLACEHOLDER_U16 '-'
#define HSML_TOKEN_PLACEHOLDER_U32 '+'
#define HSML_TOKEN_PLACEHOLDER_U64 '!'
#define HSML_TOKEN_PLACEHOLDER_STR '^'