#pragma once

typedef enum
{
    SCA_KEY_NONE = 0,
    
    /* Numbers */
    SCA_KEY_0 = 1,
    SCA_KEY_1,
    SCA_KEY_2,
    SCA_KEY_3,
    SCA_KEY_4,
    SCA_KEY_5,
    SCA_KEY_6,
    SCA_KEY_7,
    SCA_KEY_8,
    SCA_KEY_9,

    /* Letters */
    SCA_KEY_A,
    SCA_KEY_B,
    SCA_KEY_C,
    SCA_KEY_D,
    SCA_KEY_E,
    SCA_KEY_F,
    SCA_KEY_G,
    SCA_KEY_H,
    SCA_KEY_I,
    SCA_KEY_J,
    SCA_KEY_K,
    SCA_KEY_L,
    SCA_KEY_M,
    SCA_KEY_N,
    SCA_KEY_O,
    SCA_KEY_P,
    SCA_KEY_Q,
    SCA_KEY_R,
    SCA_KEY_S,
    SCA_KEY_T,
    SCA_KEY_U,
    SCA_KEY_V,
    SCA_KEY_W,
    SCA_KEY_X,
    SCA_KEY_Y,
    SCA_KEY_Z,

    /* Numpad */
    SCA_KEY_KP_0,
    SCA_KEY_KP_1,
    SCA_KEY_KP_2,
    SCA_KEY_KP_3,
    SCA_KEY_KP_4,
    SCA_KEY_KP_5,
    SCA_KEY_KP_6,
    SCA_KEY_KP_7,
    SCA_KEY_KP_8,
    SCA_KEY_KP_9,
    SCA_KEY_KP_DIVIDE,
    SCA_KEY_KP_MULTIPLY,
    SCA_KEY_KP_SUBTRACT,
    SCA_KEY_KP_ADD,
    SCA_KEY_KP_ENTER,
    SCA_KEY_KP_DECIMAL,

    /* Special keys */
    SCA_KEY_ESC,
    SCA_KEY_F1,
    SCA_KEY_F2,
    SCA_KEY_F3,
    SCA_KEY_F4,
    SCA_KEY_F5,
    SCA_KEY_F6,
    SCA_KEY_F7,
    SCA_KEY_F8,
    SCA_KEY_F9,
    SCA_KEY_F10,
    SCA_KEY_F11,
    SCA_KEY_F12,

    SCA_KEY_UP,
    SCA_KEY_DOWN,
    SCA_KEY_LEFT,
    SCA_KEY_RIGHT,

    SCA_KEY_LSHIFT,
    SCA_KEY_RSHIFT,
    SCA_KEY_LCTRL,
    SCA_KEY_RCTRL,
    SCA_KEY_LALT,
    SCA_KEY_RALT,
    SCA_KEY_SPACE,
    SCA_KEY_ENTER,
    SCA_KEY_BACKSPACE,
    SCA_KEY_TAB,
    SCA_KEY_CAPSLOCK,
    
    SCA_KEY_INS,
    SCA_KEY_DEL,
    SCA_KEY_HOME,
    SCA_KEY_END,
    SCA_KEY_PAGEUP,
    SCA_KEY_PAGEDOWN,

    SCA_KEY_COUNT
} key;