#!/bin/bash

meson configure build \
    --prefix=$(pwd)/deploy \
    -Dbuildtype=release \
    -Dbuild_loader=true \
    -Dbuild_testbed=true \
    -Duse_gl_rhi=true \
    -Duse_native_windowing=true
